/**
 * Indian medical brand → generic hints for voice UI & LLM post-processing.
 * Indicative only — verify against your hospital formulary / NMC generic prescribing rules.
 */
export const INDIAN_DRUG_BRAND_HINTS: Record<string, string> = {
  telma: 'Telmisartan',
  telmikind: 'Telmisartan',
  amlokind: 'Amlodipine',
  amlovas: 'Amlodipine',
  amlong: 'Amlodipine',
  storvas: 'Atorvastatin',
  atorva: 'Atorvastatin',
  tonact: 'Atorvastatin',
  rozavel: 'Rosuvastatin',
  rosuvas: 'Rosuvastatin',
  ecosprin: 'Aspirin (enteric coated)',
  clopilet: 'Clopidogrel',
  plavix: 'Clopidogrel',
  deplatt: 'Clopidogrel + Aspirin',
  glycomet: 'Metformin',
  gluformin: 'Metformin',
  gemer: 'Glimepiride + Metformin',
  amaryl: 'Glimepiride',
  volix: 'Voglibose',
  janumet: 'Sitagliptin + Metformin',
  januvia: 'Sitagliptin',
  istavel: 'Sitagliptin',
  trajenta: 'Linagliptin',
  galvus: 'Vildagliptin',
  lantus: 'Insulin glargine',
  basalog: 'Insulin glargine',
  mixtard: 'Biphasic insulin',
  novorapid: 'Insulin aspart',
  levemir: 'Insulin detemir',
  pantocid: 'Pantoprazole',
  pan: 'Pantoprazole',
  nexpro: 'Esomeprazole',
  nexium: 'Esomeprazole',
  omez: 'Omeprazole',
  rabekind: 'Rabeprazole',
  lanzol: 'Lansoprazole',
  aciloc: 'Ranitidine',
  rantac: 'Ranitidine',
  voveran: 'Diclofenac',
  brufen: 'Ibuprofen',
  combiflam: 'Ibuprofen + Paracetamol',
  crocin: 'Paracetamol',
  dolo: 'Paracetamol',
  calpol: 'Paracetamol',
  sinarest: 'Paracetamol + Phenylephrine + CPM',
  wikoryl: 'Paracetamol + Phenylephrine',
  asthalin: 'Salbutamol',
  foracort: 'Formoterol + Budesonide',
  seroflo: 'Salmeterol + Fluticasone',
  duolin: 'Ipratropium + Salbutamol',
  budecort: 'Budesonide',
  levolin: 'Levosalbutamol',
  montair: 'Montelukast',
  montek: 'Montelukast',
  telekast: 'Montelukast',
  allegra: 'Fexofenadine',
  okacet: 'Cetirizine',
  cetiriz: 'Cetirizine',
  avil: 'Pheniramine',
  augmentin: 'Amoxicillin + Clavulanate',
  moxikind: 'Amoxicillin',
  azithral: 'Azithromycin',
  azicip: 'Azithromycin',
  zifi: 'Cefixime',
  cefspan: 'Cefpodoxime',
  monocef: 'Ceftriaxone',
  taxim: 'Ceftriaxone',
  ciplox: 'Ciprofloxacin',
  norflox: 'Norfloxacin',
  oflox: 'Ofloxacin',
  levoflox: 'Levofloxacin',
  moxiflox: 'Moxifloxacin',
  metrogyl: 'Metronidazole',
  encorate: 'Sodium valproate',
  levipil: 'Levetiracetam',
  eptoin: 'Phenytoin',
  tegrital: 'Carbamazepine',
  gabapin: 'Gabapentin',
  eltroxin: 'Levothyroxine',
  thyronorm: 'Levothyroxine',
  thyrox: 'Levothyroxine',
  shelcal: 'Calcium + Vitamin D3',
  gemcal: 'Calcium + D3',
  ostocalcium: 'Calcium + D3',
  arachitol: 'Vitamin D3',
  depura: 'Vitamin D3',
  tayo: 'Vitamin D3',
  dexorange: 'Iron + Folic acid',
  livogen: 'Iron + Folic acid',
  tonoferon: 'Iron + Folic + B12',
  orofer: 'Iron (IV) — iron sucrose',
  folvite: 'Folic acid',
  sysfol: 'Folic acid',
  neurobion: 'Methylcobalamin + B vitamins',
  renerve: 'Methylcobalamin',
  becosules: 'B-complex + Vitamin C',
  polybion: 'B vitamins',
  limcee: 'Vitamin C',
  becadexamin: 'Multivitamin',
  supradyn: 'Multivitamin',
  zincovit: 'Multivitamin + Zinc',
  evion: 'Vitamin E',
  wysolone: 'Prednisolone',
  omnacortil: 'Prednisolone',
  dexona: 'Dexamethasone',
  betnesol: 'Betamethasone',
  tenormin: 'Atenolol',
  betacard: 'Metoprolol',
  metolar: 'Metoprolol',
  concor: 'Bisoprolol',
  nebicard: 'Nebivolol',
  betacap: 'Propranolol',
  inderal: 'Propranolol',
  olmezest: 'Olmesartan',
  losar: 'Losartan',
  dytor: 'Torsemide',
  lasix: 'Furosemide',
  aldactone: 'Spironolactone',
  sorbitrate: 'Isosorbide dinitrate',
  monit: 'Isosorbide mononitrate',
  stanlip: 'Fenofibrate',
  fibator: 'Atorvastatin + Fenofibrate',
  lipaglyn: 'Saroglitazar',
  urimax: 'Tamsulosin',
  veltam: 'Tamsulosin',
  flotral: 'Alfuzosin',
  dutas: 'Dutasteride',
  finax: 'Finasteride',
  finpecia: 'Finasteride',
  trapic: 'Tranexamic acid',
  pause: 'Tranexamic acid',
  meftal: 'Mefenamic acid',
  cyclopam: 'Dicyclomine + Paracetamol',
  spasmonil: 'Dicyclomine',
  buscopan: 'Hyoscine butylbromide',
  drotin: 'Drotaverine',
  domstal: 'Domperidone',
  ondem: 'Ondansetron',
  emeset: 'Ondansetron',
  bandy: 'Albendazole',
  zentel: 'Albendazole',
  hcqs: 'Hydroxychloroquine',
  udiliv: 'Ursodeoxycholic acid',
  ursokem: 'UDCA',
  hepamerz: 'L-ornithine L-aspartate',
  cremaffin: 'Liquid paraffin + milk of magnesia',
  duphalac: 'Lactulose',
  lactifiber: 'Ispaghula + Lactitol',
  urispas: 'Flavoxate',
  diziron: 'Cinnarizine',
  vertin: 'Betahistine',
  stemetil: 'Prochlorperazine',
  atarax: 'Hydroxyzine',
  larpose: 'Lorazepam',
  alprax: 'Alprazolam',
  zapiz: 'Clonazepam',
  lonazep: 'Clonazepam',
  feliz: 'Escitalopram',
  serlift: 'Sertraline',
  daxid: 'Sertraline',
  fludac: 'Fluoxetine',
  venlor: 'Venlafaxine',
  alex: 'Ambroxol',
  benadryl: 'Diphenhydramine',
  deriphyllin: 'Etophylline + Theophylline',
  daonil: 'Glibenclamide',
  diamicron: 'Gliclazide',
  carbimazole: 'Carbimazole',
  neo: 'Carbimazole (Neo-Mercazole)',
  prasita: 'Prasugrel',
  brilinta: 'Ticagrelor',
  human: 'Human insulin (generic)',
  regestrone: 'Norethisterone',
  ovral: 'OCP — EE + Levonorgestrel',
  ipill: 'Levonorgestrel emergency',
  unwanted: 'Levonorgestrel emergency',
  ivermectin: 'Ivermectin',
  mebendex: 'Mebendazole',
  nervijen: 'Neurotropic B vitamins',
  septilin: 'Herbal immunomodulator (OTC)',
  honitus: 'Herbal cough (OTC)',
  liv: 'Liver supplement (OTC)',
  corex: 'Codeine cough (regulated)',
  ors: 'Oral rehydration salts',
  zinc: 'Zinc tablets (ORS-Zinc)',
};

export const INDIAN_BRAND_NAMES_SORTED = Object.keys(INDIAN_DRUG_BRAND_HINTS).sort();

export function matchBrandHints(text: string, limit = 8): { brand: string; genericHint: string }[] {
  const lower = text.toLowerCase();
  return INDIAN_BRAND_NAMES_SORTED.filter((b) => lower.includes(b))
    .slice(0, limit)
    .map((brand) => ({ brand, genericHint: INDIAN_DRUG_BRAND_HINTS[brand] ?? '' }));
}
